### ISSUE TITLE
Conda install broken?

### ISSUE THREAD

**Issue by banesullivan** [jupyter-widgets/ipyleaflet#900]
I have `ipyleaflet` installed from conda in this MyBinder repo: https://github.com/banesullivan/localtileserver-demo

Where I specify `ipyleaflet` as a depend here: https://github.com/banesullivan/localtileserver-demo/blob/9684215e233c01b70f6a9398f4e8ae6f9bfa9f29/environment.yml#L16

and I'm getting this error trying to import `Map`:

```py
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_65/1135981640.py in <module>
----> 1 from ipyleaflet import Map

ImportError: cannot import name 'Map' from 'ipyleaflet' (/srv/conda/envs/notebook/lib/python3.10/site-packages/ipyleaflet/__init__.py)

```

**Comment by banesullivan** [comment]
It says that it is the latest version:
```py
import ipyleaflet
ipyleaflet.__version__
```
'0.15.0'

**Comment by banesullivan** [comment]
Launch this notebook to see the error: https://hub.gke2.mybinder.org/user/banesullivan-lo-tileserver-demo-40ntoonv/lab/tree/URL%20COG.ipynb

**Comment by davidbrochart** [comment]
Thanks for reporting @banesullivan, sorry for that! `xyzservices` was added as a dependency in the PyPI package but not in the conda package.
This is fixed in https://github.com/conda-forge/ipyleaflet-feedstock/pull/99. I also marked the current conda package for v0.15.0 as broken in https://github.com/conda-forge/admin-requests/pull/356.
You should now (or soon) be able to `mamba install ipyleaflet=0.15.0` again and it should work fine (maybe clean the cache with `mamba clean -i`).

**Comment by banesullivan** [comment]
Awesome, thanks for jumping on this so quickly! I'll mark this as closed since the new build landed on the feedstock (have yet to though)

**Comment by martinRenou** [comment]
Awesome thanks David!
